### ISSUE TITLE
JSON Export

### ISSUE THREAD

**Issue by fuerbringer** [PROGRADE-Tech/Tarchivebot#12]
I propose following feature: A button with the option to export your whole chat history as a `.json` file. 

That's the basic version. For post-[MVP](https://github.com/PROGRADE-Tech/Tarchivebot/milestone/1) builds we could even consider implementing an `Export this view` option. This would only export the current filtered/sorted contents of the table. Again, this advanced version probably shouldn't be taken into the MVP.

Thoughts?

**Comment by fuerbringer** [comment]
Would like to hear from @Hoi15A since the front-end is mostly developed by him.

**Comment by Hoi15A** [comment]
Basic export should be no problem and can probably be done in time with [MPV](https://github.com/PROGRADE-Tech/Tarchivebot/milestone/1). However exporting the sorted/filtered contents of the table already becomes slightly more tricky and would require me to do more research.

And for your export this view, this could totally be doable with the html2png library to export most graphs I imagine.

**Comment by fuerbringer** [comment]
Sounds good. Then let's try to include the basic/full export into the MVP.

**Comment by fuerbringer** [comment]
This issue was implemented in #54.
