### ISSUE TITLE
AUTHORS or CONTRIBUTORS file

### ISSUE THREAD

**Issue by fuerbringer** [PROGRADE-Tech/Tarchivebot#16]
What do you think about adding an `AUTHORS` file? People with at least one merged commit into master would be listed there with the format being `Severin Fürbringer <severin@prograde.ch` for example.

Alternatively instead of `AUTHORS` we could create the `CONTRIBUTORS` file. People who contributed in _any_ way would be listed there. Even for issues, creating artwork or similar.

This might also encourage people to contribute to this repository. Thoughts?

**Comment by GianlucaScarciolla** [comment]
I prefer the `CONTRIBUTORS` file.

**Comment by Hoi15A** [comment]
I agree with @GianlucaScarciolla about preferring the `CONTRIBUTORS`.
What we could do though is split the file up so we have for example:

> Creators:
> John Doe
> John Doe2
>
> Members:
> (aka ppl that have coded shit, which also happens on git repos already if you check users)
>
> Other contributions:
> Hugh Mungus <mail.mungus@hugh.com> - Issue #X 
> Some guy <kek@abc.com> - Logo art

**Comment by fuerbringer** [comment]
I too would prefer the `CONTRIBUTORS` file. But I'm not sure about that format @Hoi15A.
With files like `CONTRIBUTORS` or `AUTHORS` the common syntax is this:

> Severin Fürbringer <severin@prograde.ch>

[Here](https://github.com/nodejs/node/blob/master/AUTHORS) is an example from a big project.

But if @GianlucaScarciolla would also prefer the more detailed format by @Hoi15A then we'll go with that.

**Comment by GianlucaScarciolla** [comment]
@fuerbringer I would say we go with the more detailed format.

**Comment by fuerbringer** [comment]
Alright. In that case I'd suggest we create the file in the Markdown format. Since this is something small I'll put this into the MVP milestone.

@Hoi15A Feel free to create a PR.
