### ISSUE TITLE
Description with screenshots

### ISSUE THREAD

**Issue by GianlucaScarciolla** [PROGRADE-Tech/Tarchivebot#33]
Please provide a **Description** for Tarchivebot.

- [ ] **Description** (What it does, how and Why you should use it)
- [ ]  **Features** (With FontAwesome icons (for website later))
- [x] Some **Screenshots** (Telegram Chat _bot_ and Admin Interface)

Thanks 👍

**Comment by fuerbringer** [comment]
A screenshot has been added to the README as of https://github.com/PROGRADE-Tech/Tarchivebot/commit/69a1a89b77ee91feb8924e8fb99890c6e2c915c9.
