### ISSUE TITLE
Custom application icon

### ISSUE THREAD

**Issue by fuerbringer** [PROGRADE-Tech/Tarchivebot#36]
Make a unique icon for Tarchive and implement it in the front end.

**Comment by GianlucaScarciolla** [comment]
I will create a unique icon for Tarchive. Some desired color?

**Comment by fuerbringer** [comment]
There's some colours you could use in your palette. Since our project is heavily dependant on Telegram, why not use their colour? Maybe you could come up with something creative. Alternatively you could use the PROGRADE Tech colours, which I assume you already have.

![Telegram Logo](https://telegram.org/img/t_logo.png)

If you've made some progress or just need feedback, feel free to post your results here.

**Comment by fuerbringer** [comment]
Closed by #62
