### ISSUE TITLE
Front end sends /api/recent request with no key present

### ISSUE THREAD

**Issue by fuerbringer** [PROGRADE-Tech/Tarchivebot#45]
The front end seems to immidiately send a request to `/api/recent` on a completely fresh page load (with no key in localstorage present).

_TLDR:_ This shouldn't happen: (_https://a.doko.moe/qpuzpt.png_)
![tarchive bug](https://a.doko.moe/qpuzpt.png)

**Comment by fuerbringer** [comment]
Im not an Angular dev, but could **[this](https://github.com/PROGRADE-Tech/Tarchivebot/blob/master/public/js/core.js#L17)** be the cause? The callback seems to be declared on line `11` and immidiately called on line `17`. Shouldn't it be inside an `if` statement to check if an API key is present? @Hoi15A

**Comment by Hoi15A** [comment]
That's likely it, I'll deal with it once I get around to this issue.

**Comment by fuerbringer** [comment]
As a follow up: The `if` statement should not only check if the key is present but also if it's valid. Ofcourse for that [an API-Call](https://github.com/PROGRADE-Tech/Tarchivebot/blob/master/docs/API.md#apivalidatekey) already exists and is ready to be used.

**Comment by fuerbringer** [comment]
Fixed in 59df19e2881cd728a06d61fd9bd719868781a6c5.
