### ISSUE TITLE
Frontend idea collection

### ISSUE THREAD

**Issue by Hoi15A** [PROGRADE-Tech/Tarchivebot#6]
Please leave your ideas on what should be implemented on the front end of Tarchive.

Write down a short description of what you want to be implemented and how you expect it to work.

Example (and also actual idea):

> Idea: Multiple keys can be used at once to gather data from multiple chats. The keys would all be stored in localstorage and the user can select them from a small panel or similar. The combining of the data can be done both on the front/backend.
Library that could be used: [None needed for this case]

**Comment by Hoi15A** [comment]
Here's another idea: A word cloud graph that displays word frequency of your chat. This would be a graph that shows up in the same place as the table does and also has a small section below with the words and their exact numbers. This data would be best provided from the backend.

**Comment by GianlucaScarciolla** [comment]
An area spline graph that displays when users chat the most. This would be a graph that shows up in the same place (like the Cloud graph) as the table does and also has a small section below with the users and their exact timestamp.

**Comment by fuerbringer** [comment]
@Hoi15A Excellent thinking. This is what I was imagining for the first frontend feature. 🚀 
@GianlucaScarciolla Although not as important as the already mentioned wordcount, this is also a great idea.

It would be great if you could list the frontend libraries for displaying those graphs, because I don't currently know of any we could use.

**Comment by Hoi15A** [comment]
@fuerbringer updated my word cloud idea with a potential library.

**Comment by GianlucaScarciolla** [comment]
@Hoi15A I've added an example.

**Comment by fuerbringer** [comment]
Excellent example. @Hoi15A shall we consider implementing the usage-graph example by @GianlucaScarciolla into the  [MVP mileston](https://github.com/PROGRADE-Tech/Tarchivebot/milestone/1)e? This would ofcourse be on-top of the regular word-count list.

**Comment by fuerbringer** [comment]
I'll be closing this issue so we can split it up into multiple issues later on because there's some great ideas we've gathered so far which probably need further discussion. 🚀

**Comment by Hoi15A** [comment]
Split up issues:
[Multi-key](https://github.com/PROGRADE-Tech/Tarchivebot/issues/9)

**Comment by Hoi15A** [comment]
@GianlucaScarciolla it would be nice if you could split your idea into its own issue :) I will take care of tagging it appropriately
